### ISSUE TITLE
is_contained for chromosome arms broken?

### ISSUE THREAD

**Issue by Phlya** [open2c/bioframe#118]
```python
>>> view
   chrom     start        end    name
0  chr2          0   93139351  chr2_p
1  chr2   93139351  242193529  chr2_q
>>> clr_view
   chrom  start        end   name
0   chr2      0  242193529   chr2
1  chr17      0   83257441  chr17
>>> bioframe.is_contained(view, clr_view, raise_errors=True)
Traceback (most recent call last):
  File "/Users/ilya/opt/anaconda3/envs/open2cdev/lib/python3.8/site-packages/bioframe/core/checks.py", line 289, in is_contained
    assert (df_view_assigned["end_"].isna()).sum() == 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilya/opt/anaconda3/envs/open2cdev/lib/python3.8/site-packages/bioframe/core/checks.py", line 295, in is_contained
    raise AssertionError("df not contained in view_df")
AssertionError: df not contained in view_df
```
And I think it's because this doesn't work as I would expect it to...
```python
>>> bioframe.assign_view(view, clr_view)
   chrom     start        end    name view_region
0  chr2          0   93139351  chr2_p        None
1  chr2   93139351  242193529  chr2_q        None
```

FYI all this causes is_compatible_viewframe(view, clr) to break, and hence e.g. dots can't be called on arms :(

```python
>>> cooltools.lib.checks.is_compatible_viewframe(view, clr, raise_errors=True)
Traceback (most recent call last):
  File "/Users/ilya/opt/anaconda3/envs/open2cdev/lib/python3.8/site-packages/cooltools/lib/checks.py", line 446, in is_compatible_viewframe
    raise ValueError(
ValueError: View table is out of the bounds of chromosomes in cooler.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilya/opt/anaconda3/envs/open2cdev/lib/python3.8/site-packages/cooltools/lib/checks.py", line 460, in is_compatible_viewframe
    raise ValueError("view_df is not compatible, or not a viewframe") from e
ValueError: view_df is not compatible, or not a viewframe
```

**Comment by Phlya** [comment]
@gfudenberg shall we continue here?

I am still having the problem, I reinstalled bioframe 3.3 from pip even.

Now I tried a view with both chromosomes, and actually the chr17 arms do get assigned... which is even weirder? But still chr2 `None`s cause a problem with `is_contained`, which in turn breaks things that check compatibility of viewframe with a cooler...
```python
>>> clr_view
   chrom  start        end   name
0   chr2      0  242193529   chr2
1  chr17      0   83257441  chr17
>>> view
   chrom     start        end     name
0  chr2          0   93139351   chr2_p
1  chr2   93139351  242193529   chr2_q
2  chr17         0   24714921  chr17_p
3  chr17  24714921   83257441  chr17_q
>>> bioframe.assign_view(view, clr_view)
   chrom     start        end     name view_region
0  chr2          0   93139351   chr2_p        None
1  chr2   93139351  242193529   chr2_q        None
2  chr17         0   24714921  chr17_p       chr17
3  chr17  24714921   83257441  chr17_q       chr17
```

**Comment by agalitsyna** [comment]
With the recent 0.3.3 version of GitHub version of bioframe, works perfect: 
<img src="https://user-images.githubusercontent.com/8100372/182687271-89dd564e-6324-45d2-8082-03041369b38f.png" alt="Code" width="300" height="400">

Other relevant software versions: 
```
>>> pd.__version__, np.__version__ 
('1.4.2', '1.21.6')
```

**Comment by Phlya** [comment]
Sorted it out! Had some stupid spaces in the file for some reason, everything works as it should. False alarm, sorry!
